# Generated by Django 5.1.3 on 2024-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('checked', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('dimensions', models.TextField(blank=True)),
                ('per_man_link', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
