from django.urls import path
from .views import (
    HomeView,
    users,
    order_list,
    order_detail,
    order_tracking,
    add_new_product,
    all_users,
    coupon_list,
    create_coupon,
    create_menu,
    create_vendor,
    currency_rates,
    forgot_password,
    invoice,
    list_page,
    login,
    menu_lists,
    product_review,
    products,
    profile_setting,
    reports,
    sign_up,
    support_ticket,
    taxes,
    add_new_user,
    translation,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('users/', users, name='users'),
    path('add-new-user', add_new_user, name='add_new_user'),
    path('add-new-product/', add_new_product, name='add-new-product'),
    path('all-users/', all_users, name='all-users'),
    path('coupon-list/', coupon_list, name='coupon-list'),
    path('create-coupon/', create_coupon, name='create-coupon'),
    path('create-menu/', create_menu, name='create-menu'),
    path('create-vendor/', create_vendor, name='create-vendor'),
    path('currency-rates/', currency_rates, name='currency-rates'),
    path('forgot-password/', forgot_password, name='forgot-password'),
    path('invoice/', invoice, name='invoice'),
    path('list-page/', list_page, name='list-page'),
    path('login/', login, name='login'),
    path('menu-lists/', menu_lists, name='menu-lists'),
    path('order-detail/', order_detail, name='order-detail'),
    path('order-list/', order_list, name='order-list'),
    path('order-tracking/', order_tracking, name='order-tracking'),
    path('product-review/', product_review, name='product-review'),
    path('products/', products, name='products'),
    path('profile-setting/', profile_setting, name='profile-setting'),
    path('reports/', reports, name='reports'),
    path('sign-up/', sign_up, name='sign-up'),
    path('support-ticket/', support_ticket, name='support-ticket'),
    path('taxes/', taxes, name='taxes'),
    path('translation/', translation, name='translation'),
]
